exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('variety').del()
    .then(function () {
      // Inserts seed entries
      return knex('variety').insert([
        {id: 1, 
         variety_name: 'Amish Gold',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'medium/large',
         maturity_days: 85
        },
        {id: 2, 
         variety_name: 'Baller',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'small',
         maturity_days: 71
        },
        {id: 3, 
         variety_name: 'Berwick German',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'medium',
         maturity_days: 85
        },
        {id: 4, 
         variety_name: 'Big Rainbow',
         species: 'Tomato',
         fruit_color: 'orange yellow',
         size: 'large',
         maturity_days: 82
        },
        {id: 5, 
         variety_name: 'Black Ethiopian',
         species: 'Tomato',
         fruit_color: 'purple black',
         size: 'small',
         maturity_days: 81
        },
        {id: 6, 
         variety_name: 'Black Plum',
         species: 'Tomato',
         fruit_color: 'Mahogany',
         size: 'small',
         maturity_days: 72
        },
        {id: 7, 
         variety_name: 'Brandywine OTV',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'large',
         maturity_days: 72
        },
        {id: 8, 
         variety_name: 'Brown\'s Yellow Giant',
         species: 'Tomato',
         fruit_color: 'Orange Yellow',
         size: 'large',
         maturity_days: 90
        },
        {id: 9, 
         variety_name: 'Cherokee Chocolate',
         species: 'Tomato',
         fruit_color: 'black brown',
         size: 'medium',
         maturity_days: 80
        },
        {id: 10, 
         variety_name: 'Costoluto Ganovesse',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'large',
         maturity_days: 78
        },
        {id: 11, 
         variety_name: 'Delicious',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'very large',
         maturity_days: 77
        },
        {id: 12, 
         variety_name: 'Ed\'s Fat Plum',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'medium',
         maturity_days: 80,
         description: 'A German variety, which can be used as a salad tomato or appetizer. Plants produce an abundance of medium slender plum. Flesh is juicy, semi-sweet with unmatched flavor. Rare, easy to grow and productive.',
         variety_image: 'css/img/eds_fat_plum.jpg'
        },
        {id: 13, 
         variety_name: 'Evergreen',
         species: 'Tomato',
         fruit_color: 'green',
         size: 'medium',
         maturity_days: 75
        },
        {id: 14, 
         variety_name: 'Fantastic',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'medium',
         maturity_days: 85
        },
        {id: 15, 
         variety_name: 'Flamme',
         species: 'Tomato',
         fruit_color: 'orange',
         size: 'small',
         maturity_days: 70
        },
        {id: 16, 
         variety_name: 'Georgia Streak',
         species: 'Tomato',
         fruit_color: 'gold Red',
         size: 'large',
         maturity_days: 90
        },
        {id: 17, 
         variety_name: 'German Johnson',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'large',
         maturity_days: 80
        },
        {id: 18, 
         variety_name: 'German Strip',
         species: 'Tomato',
         fruit_color: 'orange yellow',
         size: 'very large',
         maturity_days: 78
        },
        {id: 19, 
         variety_name: 'Giant Belgium',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'very large',
         maturity_days: 75
        },
        {id: 20, 
         variety_name: 'God Love',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'cherry',
         maturity_days: 75
        },
        {id: 21, 
         variety_name: 'Haidi?',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'small',
         maturity_days:75
        },
        {id: 22, 
         variety_name: 'Hess',
         species: 'Tomato',
         fruit_color: 'yellow',
         size: 'large',
         maturity_days: 85
        },
        {id: 23, 
         variety_name: 'Julia Child',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'small',
         maturity_days: 85
        },
        {id: 24, 
         variety_name: 'Lida Ukrainian',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'small',
         maturity_days: 75
        },
        {id: 25, 
         variety_name: 'Marizol BratKa',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'large',
         maturity_days: 85
        },
        {id: 26, 
         variety_name: 'Marizol Gold',
         species: 'Tomato',
         fruit_color: 'gold-red',
         size: 'large',
         maturity_days: 90
        },
        {id: 27, 
         variety_name: 'Marz Yellow-Red',
         species: 'Tomato',
         fruit_color: 'yellow red',
         size: 'medium',
         maturity_days: 80,
         description: 'This is an offtype of Marz Green that appeared in some growouts by different SSE members. It seems like the Marz Green seeds released around 2005 were not entirely stable, and gave a variety of striped segregation lines. Very good flavor.',
         variety_image: "css/img/marz.jpg"
        },
        {id: 28, 
         variety_name: 'New Zealand Pink',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'large',
         maturity_days: 90
        },
        {id: 29, 
         variety_name: 'Orange Beefsteak',
         species: 'Tomato',
         fruit_color: 'orange yellow',
         size: 'large',
         maturity_days: 79
        },
        {id: 30, 
         variety_name: 'Orange Russian 117',
         species: 'Tomato',
         fruit_color: 'gold red',
         size: 'medium',
         maturity_days: 85
        },
        {id: 31, 
         variety_name: 'Oxheart',
         species: 'Tomato',
         fruit_color: 'pink',
         size: 'large',
         maturity_days: 80
        },
        {id: 32, 
         variety_name: 'Paul Robeson',
         species: 'Tomato',
         fruit_color: 'purple black',
         size: 'medium',
         maturity_days: 74
        },
        {id: 33, 
         variety_name: 'Radiator Charlie',
         species: 'Tomato',
         fruit_color: 'red pink',
         size: 'very large',
         maturity_days: 80
        },
        {id: 34, 
         variety_name: 'Red Pear',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'cherry',
         maturity_days: 70
        },
        {id: 35, 
         variety_name: 'Rivieria',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'medium',
         maturity_days: 74
        },
        {id: 36, 
         variety_name: 'Sunset Red Horizon',
         species: 'Tomato',
         fruit_color: 'red',
         size: 'large',
         maturity_days: 72,
         description: 'The original variety, Rostova, is a heirloom red beefsteak from Southern Russia that was introduced to the west by Nik Peplenov who immigrated to the US in 1999 and brought with him his favorite heirloom seeds from the Rostov, Don region of Russia.',
         variety_image: 'css/img/sunset.jpg'
        },
        {id: 37, 
         variety_name: 'White',
         species: 'Tomato',
         fruit_color: 'white',
         size: 'large',
         maturity_days: 80
        },
        {id: 38, 
         variety_name: 'Yellow Gooseberry',
         species: 'Tomato',
         fruit_color: 'orange yellow',
         size: 'cherry',
         maturity_days: 75
        },
        {id: 39, 
         variety_name: 'Yellow Ruffled',
         species: 'Tomato',
         fruit_color: 'orange yellow',
         size: 'medium',
         maturity_days: 80
        },
        {id: 40, 
         variety_name: 'Zapotec Pleated',
         species: 'Tomato',
         fruit_color: 'pink red',
         size: 'medium',
         maturity_days: 85
        }
      ]);
    })
    .then(() => {
            return knex.raw(
                "SELECT setval('variety_id_seq', (SELECT MAX(id) FROM variety));"
            );
        });
};